### ISSUE TITLE
For SIMD / “Bar Chart” style & Census / “Bar Chart” style, change chart to normalised stacked bars

### ISSUE THREAD

**Issue by kidwellj** [ahmednoureldeen/common-ground_map#1]
For these charts, data should represent overall distribution of points across quintiles using normalised stacked bars (total 100% for all groups). Example of chart style here: https://bl.ocks.org/mbostock/3886394.

For SIMD deprivation quintiles (bottom to top) rank at: 
First quintile: 1-1395
Second quintile: 1396-2790
Third quintile: 2791-4185
Fourth quintile: 4186-5580
Fifth quintile: 5581-6976

Stacking on bars for census11 should follow categories (as shown in the following):

![barchart_census_spec](https://user-images.githubusercontent.com/790736/30251861-3284adde-9660-11e7-8767-19f8d6352178.png)

**Comment by ahmednoureldeen** [comment]
check it

**Comment by kidwellj** [comment]
That's the ticket. Census11 Bar-charts are looking just right. Can we get UrbanRural and SIMD to show colours for different stacks on each bar in the same way?

**Comment by ahmednoureldeen** [comment]
legend will show only one color for one column ('rank', 'emprank'...etc).
so if we have have chart bar with different colors for each bar it will be inconvenient.
so for now i set different color for each chart. check it.

**Comment by kidwellj** [comment]
This is a crucial feature - each bar needs to show distribution (by rank) in UrbanRural and quantile in SIMD for bars. What's preventing colours from working? Can we use something like https://github.com/bmschmidt/colorbar?

**Comment by kidwellj** [comment]
If absolutely impossible to do stacked bars, I could live with grouped bars: https://bl.ocks.org/mbostock/3887051.

**Comment by ahmednoureldeen** [comment]
it is not a matter of possibility, to get the issue clear send a sample bar chart for SIMD

**Comment by kidwellj** [comment]
This is looking very good now. The only remaining issue is that Quartiles are out of order in the stack - currently Q 31245. Can we arrange with Q1 on the bottom, then Q2, Q3, Q4, and Q5 at the top?

**Comment by ahmednoureldeen** [comment]
done
