### ISSUE TITLE
Show full y-axis titles on hover

### ISSUE THREAD

**Issue by kidwellj** [ahmednoureldeen/common-ground_map#4]
For Urban-Rural and Census11 tables, can we have longer name for Y-axis labels show on hover. 

Urban-Rural long-form category labels should be the following:

U1	Large Urban Areas
U2	Smaller Urban Areas
R1	Accessible Settlements
R2	Sparse/Remote Settlements
R3	Accessible Villages/Dwellings
R4	Sparse/Remote Villages/Dwellings

**Comment by kidwellj** [comment]
For census, long-form category labels should be the following:

health:
VGHealth | Very good health
Ghealth | Good health
FairHealth | Fair health
BadHealth | Bad health
VBadHealth | Very bad health

economic:
EAEmpPT | Economically active: Employee: Part-time
EAEmpFT | Economically active: Employee: Full-time
EASelfEmp | Economically active: Self-employed
EAUnemp | Economically active: Unemployed
EAFuTiSt | Economically inactive: Full time student
EIRetired | Economically inactive: Retired
EIFuTiSt | Economically inactive: Student (including full-time students)
EIHome | Economically inactive: Looking after home or family
EISickDis | Economically inactive: Long-term sick or disabled
EIOther | Economically inactive: Other

industry:
Agricult | A Agriculture, forestry and fishing
Extractive | B Mining and quarrying
Manufact | C Manufacturing
EnergySup | D Electricity, gas, steam and air conditioning supply
WaterSup | E Water supply; sewerage, waste management and remediation activities
Construct | F Construction
Retail | G Wholesale and retail trade; repair of motor vehicles and motor cycles
Transport | H Transport and storage
Accomm Food | I Accommodation and food service activities
InfoComms | J Information and communication
FinServ | K Financial and insurance activities
PropServ | L Real estate activities
ProfTech | M Professional, scientific and technical activities
Administ | N Administrative and support service activities
PubAdDef | O Public administration and defence; compulsory social security
Education | P Education
Health | Q Human health and social work activities
OtherInd | R S T and U Other

work travel:

TTWHome | Work mainly at or from home
TTWTrain | Train
TTWTube | Underground metro light rail tram
TTWBus | Bus minibus or coach
TTWMBike | Motorcycle, scooter or moped
TTWCar | Driving a car or van
TTWCarPass | Passenger in a car or van including car share
TTWTaxi | Taxi
TTWBike | Bicycle
TTWFoot | On foot
TTWOther | Other method of travel to work

**Comment by ahmednoureldeen** [comment]
check it

**Comment by kidwellj** [comment]
Tool tips work great (if a little lagged?). Thanks.

Would it be possible to get them to display on hover over the legend box/labels below chart as well?

**Comment by ahmednoureldeen** [comment]
although it is not supported by c3 but i find my way to do it for legend, but i think we can't for labels.

**Comment by kidwellj** [comment]
Ok - I'll see about whether we can find another way to provide a legend clarifying abbreviations w/ a tooltip.
