### ISSUE TITLE
Urban-Rural / Box-plot - need to reconfigure data

### ISSUE THREAD

**Issue by kidwellj** [ahmednoureldeen/common-ground_map#6]
What are bars currently representing? Can we assign numeric value to categories (U1=1, U2=2, R1=3, etc) and simply label Most Urban ==> Most Rural for Y-Axis?

**Comment by ahmednoureldeen** [comment]
that is what i actually doing.

**Comment by kidwellj** [comment]
Ok - let's leave this one for now then; just not very readable is the problem I think.
