### ISSUE TITLE
Box-plots on census11 non-existent

### ISSUE THREAD

**Issue by kidwellj** [ahmednoureldeen/common-ground_map#7]
Do we need to filter extreme outliers? Not sure what's going on here, but no bars showing.

**Comment by ahmednoureldeen** [comment]
each group in census data has multiple y variables (vhealth, ghealth...). how it will represented using boxplot.

**Comment by kidwellj** [comment]
Good point. Can we just hide boxplot option when census11 is selected?

**Comment by ahmednoureldeen** [comment]
done
